project:
  type: website

website:
  title: "Bruno Ferenc Segedin"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv.qmd
    right:
      - icon: github
        href: https://github.com/ferencsegedinbruno
format:
  html:
    css: styles.css


site-url: https://ferencsegedinbruno.github.io/<your-repo>/
